# Generated by Django 5.1.3 on 2024-11-08 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0003_convidados'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentes',
            name='reservado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noivos.convidados'),
        ),
    ]
